server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: keystore.p12
    key-alias: tomcat
    key-store-password: 123456
  port: 443

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.jackson2: INFO
